import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StatusBar from "./_components/navigation/StatusBar";
import BottomNavbar from "./_components/navigation/BottomNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-donatio-cream flex h-screen flex-col w-full`}
      >
        <StatusBar />
        {children}
        <BottomNavbar />
      </body>
    </html>
  );
}
